name: Build Python Script for AArch64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu
          pip install pyinstaller

      - name: Build Python Script with PyInstaller
        run: |
          pyinstaller --onefile your_script.py

      - name: Upload the compiled binary
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-binary
          path: dist/your_script
